author: Kathrin Gruber
markdown: kramdown
title: Introduction to R
description: Programming with R for FAECTOR
theme: minima
permalink: /:categories/

header_pages:
  - A_Primer_on_R.md
  - Base_R.md
  - Data_import.md
  - Programming_Functions.md
  - Programming_Loops.md
  - Grammer_of_Graphics.md
